steps:
  - name: 'gcr.io/cloud-builders/git'
    id: fetch_full_repository
    entrypoint: 'bash'
    args:
      - -c
      - |
        git fetch --unshallow origin $COMMIT_SHA
        git pull
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_install
    args:
      - install
  - name: 'gcr.io/cloud-builders/npm'
    id: commitlint
    entrypoint: 'bash'
    args:
      - -c
      - |
        git status
        npx commitlint --from HEAD~1 --to HEAD --verbose
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_run_build
    args:
      - run
      - build
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_run_lint
    args:
      - run
      - lint
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_run_test
    args:
      - run
      - test
