steps:
  - name: 'gcr.io/cloud-builders/git'
    id: fetch_full_repository
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd /dev-files/
        git clone https://github.com/Bluebird-Parking/bluebird-parking-seed.git
        cd bluebird-parking-seed
        git checkout $BRANCH_NAME
    volumes:
      - name: 'dev-files'
        path: /dev-files
  - name: 'gcr.io/cloud-builders/npm'
    id: commitlint
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd /dev-files/bluebird-parking-seed/
        git status
        npm install -g @commitlint/{config-conventional,cli}
        npx commitlint --from HEAD~1 --to HEAD --verbose
    volumes:
      - name: 'dev-files'
        path: /dev-files
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_install
    args:
      - install
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_run_build
    args:
      - run
      - build
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_run_lint
    args:
      - run
      - lint
  - name: 'gcr.io/cloud-builders/npm'
    id: npm_run_test
    args:
      - run
      - test
  - name: 'gcr.io/cloud-builders/npm'
    id: semantic_release
    args:
      - npx
      - semantic-release
      - -d
    secretEnv: ['GH_TOKEN', 'NPM_TOKEN']
secrets:
  - kmsKeyName: projects/bluebird-training/locations/global/keyRings/bluebird/cryptoKeys/bluebird-crypto
    secretEnv:
      GH_TOKEN: CiQA6proVI0rITq5HiD7oZcJ2D+TF4ogJkNL71i1FPqDevuSPhkSUQDJnF9TCTBsqFcugmEauSbfpNww81sgTQpx2P5IaVpZoynlKP7lqV4B7y95oF9Xkbv9g0hsWpx4GEDRCWR/Qj6zEKfiATTcoFEbfh89ZFxUnA==
      NPM_TOKEN: CiQA6proVJB4LEkv4koMrS+EgSJDp5mD2BnZnvc+Z+p5NWVZcAgSTQDJnF9TpLaa3kBi+uoBXxgluuG5lw2xC7S3vgU9tIC6OFExllifqaSz9V0m69aWtqV+sHATRxDs47CxyMRUisFheUDPUOUK1A5I6C2N
